

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kpis
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  metrics-exporter:
    build:
      context: ./metrics-exporter
    container_name: metrics-exporter
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - postgres
      - prometheus
    networks:
      - monitoring

  data-generator:
    build:
      context: ./data-generator
    container_name: data-generator
    restart: "no"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=kpis
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass123
    depends_on:
      - postgres
    networks:
      - monitoring

  sheets-exporter:
    build:
      context: ./solution
    container_name: sheets-exporter
    environment:
      - PYTHONPATH=/app
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=kpis
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass123
      - POSTGRES_PORT=5432
      - PROM_URL=http://prometheus:9090
      - GOOGLE_SHEET_ID=1qLj25khFkq9CREaK4f1GxsHmrQ_8k9W_Ptjp-Ar46uE
    depends_on:
      - postgres
      - prometheus
    networks:
      - monitoring
    volumes:
      - ./solution:/app

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge 